name: Build AppImage

on:
  release:
    types: [published]
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pkgforge-dev/archlinux:latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build AppImage
        run: sh make-anyimage.sh

      - name: Upload AppImage to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/dist/*.AppImage
            build/dist/*.AppImage.zsync

      - name: Upload AppImage as artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: WPS-Office-AppImage
          path: build/dist/*.AppImage
